apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  volumeName: mysql-pv
  accessModes:
    - ReadWriteMany
#    - ReadWriteOnceOnce
  storageClassName: ""
#  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
