apiVersion: v1
kind: Secret
metadata:
  name: msvc-users
type: Opaque
data:
  username: cm9vdA==
  password: c2FzYQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: msvc-courses
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: c2FzYQ==